RDVMEDECINS/RDVMEDECINS/Controllers/RDVMEDECINSController.cs
using RDVMEDECINS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RDVMEDECINS.Controllers
{
    public class RDVMEDECINSController : Controller
    {
        DBRDVMEDECINSEntities cx = new DBRDVMEDECINSEntities();
        // GET: RDVMEDECINS
        public ActionResult Index()
        {
            List<MEDECINS> lMed = new List<MEDECINS>();
            foreach (var item in cx.MEDECINS)
            {
                lMed.Add(item);
            }
            return View(lMed);
        }

        [HttpPost]
        public ActionResult Calendrier(int idMed,DateTime jour)
        {
            MEDECINS med = cx.MEDECINS.Single(x => x.ID == idMed);
            ViewData["idMed"] = idMed;
            ViewData["titreMed"] = med.TITRE;
            ViewData["nomMed"] = med.NOM;
            ViewData["prenomMed"] = med.PRENOM;
            ViewData["jour"] = jour;
            List<RV> lRV = new List<RV>();
            foreach (var item in cx.RV.Where(x => x.CRENEAUX.ID_MEDECIN == idMed && x.JOUR == jour))
            {
                lRV.Add(item);
            }
            return View(lRV);
        }

        [HttpGet]
        public ActionResult Reserver(int idMed,int hDebut, int mDebut, int hFin, int mFin, DateTime jour)
        {
            MEDECINS med = new MEDECINS();
            med = cx.MEDECINS.Single(x => x.ID == idMed);
            ViewData["idMed"] = idMed;
            ViewData["titreMed"] = med.TITRE;
            ViewData["nomMed"] = med.NOM;
            ViewData["prenomMed"] = med.PRENOM;
            ViewData["hDebut"] = hDebut;
            ViewData["mDebut"] = mDebut;
            ViewData["hFin"] = hFin;
            ViewData["mFin"] = mFin;
            ViewData["jour"] = jour;
            List<CLIENTS> lCl = new List<CLIENTS>();
            foreach (var item in cx.CLIENTS)
            {
                lCl.Add(item);
            }
            return View(lCl);
        }

        [HttpPost]
        public ActionResult Reserver(int idClient, int idMed, int hDebut, int mDebut, int hFin, int mFin, DateTime jour)
        {
            CRENEAUX cr = new CRENEAUX() { ID = (int)cx.CRENEAUX.Max(x => x.ID) + 1, HDEBUT = hDebut, MDEBUT = mDebut, HFIN = hFin, MFIN = mFin, ID_MEDECIN = idMed };
            cr.MEDECINS = cx.MEDECINS.Single(x => x.ID == idMed);
            RV rv = new RV() { ID = (int)cx.RV.Max(x => x.ID) + 1, ID_CLIENT = idClient, ID_CRENEAU = cr.ID, JOUR = jour };
            rv.CRENEAUX = cr;
            rv.CLIENTS = cx.CLIENTS.Single(x => x.ID == idClient);
            cx.CRENEAUX.Add(cr);
            cx.RV.Add(rv);
            cx.SaveChanges();
            List<RV> lRv = new List<RV>();
            foreach (var item in cx.RV.Where(x => x.CRENEAUX.ID_MEDECIN == cr.ID_MEDECIN && x.JOUR == rv.JOUR))
            {
                lRv.Add(item);
            }
            MEDECINS med = cx.MEDECINS.Single(x => x.ID == idMed);
            ViewData["idMed"] = idMed;
            ViewData["titreMed"] = med.TITRE;
            ViewData["nomMed"] = med.NOM;
            ViewData["prenomMed"] = med.PRENOM;
            ViewData["jour"] = jour;
            return View("Calendrier", lRv);
        }
        
        public ActionResult NouveauClient(int idMed, int hDebut, int mDebut, int hFin, int mFin, DateTime jour)
        {
            ViewData["idMed"] = idMed;
            ViewData["hDebut"] = hDebut;
            ViewData["mDebut"] = mDebut;
            ViewData["hFin"] = hFin;
            ViewData["mFin"] = mFin;
            ViewData["jour"] = jour;
            return View();
        }

        [HttpPost]
        public ActionResult NouveauClient(string titreClient, string nomClient, string prenomClient, int idMed, int hDebut, int mDebut, int hFin, int mFin, DateTime jour)
        {
            CLIENTS cl = new CLIENTS() { ID = cx.CLIENTS.Max(x => x.ID) + 1, TITRE = titreClient, NOM = nomClient, PRENOM = prenomClient };
            cx.CLIENTS.Add(cl);
            cx.SaveChanges();
            ViewData["idMed"] = idMed;
            ViewData["hDebut"] = hDebut;
            ViewData["mDebut"] = mDebut;
            ViewData["hFin"] = hFin;
            ViewData["mFin"] = mFin;
            ViewData["jour"] = jour;
            return RedirectToAction("Reserver",new { idMed, hDebut, mDebut, hFin, mFin, jour });
        }

        public ActionResult Supprimer(int idRv,int idCl,int idCr,DateTime jour)
        {
            CLIENTS cl = cx.CLIENTS.ToList().Single(x=>x.ID==idCl);
            CRENEAUX cr = cx.CRENEAUX.ToList().Single(x=>x.ID==idCr);
            ViewData["nomClient"] = cl.NOM;
            ViewData["prenomClient"] = cl.PRENOM;
            ViewData["jour"] = jour;
            ViewData["hFin"] = cr.HFIN;
            ViewData["mFin"] = cr.MFIN;
            ViewData["hDebut"] = cr.HDEBUT;
            ViewData["mDebut"] = cr.MDEBUT;
            ViewData["idRv"] = idRv;
            ViewData["idCr"] = idCr;
            return View();
        }

        [HttpPost]
        public ActionResult Supprimer(int idRv, int idCr)
        {
            RV rv = cx.RV.Single(x => x.ID == idRv);
            CRENEAUX cr = cx.CRENEAUX.Single(x => x.ID == idCr);
            MEDECINS med = cx.MEDECINS.Single(x => x.ID == cr.MEDECINS.ID);
            int idMed = (int)cr.ID_MEDECIN;
            DateTime jour = (DateTime)rv.JOUR;
            ViewData["idMed"] = idMed;
            ViewData["titreMed"] = med.TITRE;
            ViewData["nomMed"] = med.NOM;
            ViewData["prenomMed"] = med.PRENOM;
            ViewData["jour"] = jour;
            cx.RV.Remove(rv);
            cx.SaveChanges();
            cx.CRENEAUX.Remove(cr);
            cx.SaveChanges();
            List<RV> lRv = new List<RV>();
            foreach (var item in cx.RV.Where(x => x.CRENEAUX.ID_MEDECIN == idMed && x.JOUR == jour))
            {
                lRv.Add(item);
            }
            return View("Calendrier", lRv);
        }
    }
}

RDVMEDECINS/RDVMEDECINS/Views/RDVMEDECINS/Calendrier.cshtml
@model List<RDVMEDECINS.Models.RV>

@{
    ViewBag.Title = "Calendrier";
}

<h2>Cabinet médical - LES MEDECINS ASSOCIES</h2>

<input type="button" value="Accueil" onclick="location.href='./Index'" />

@{DateTime d = (DateTime)ViewData["jour"];}
<p>Rendez-vous de @ViewData["titreMed"] @ViewData["nomMed"] @ViewData["prenomMed"] le @d.ToShortDateString() </p>

<table>
    <tr>
        <th style="width:200px">
            Créneau Horaire
        </th>
        <th style="width:300px">
            Client
        </th>
        <th style="width:200px">
            Action
        </th>
    </tr>
    @for (int h = 8; h < 18;)
    {
        for (int m = 1; m != 0;)
        {
            <tr>
                <td>
                    @*Afficher les créneaux horaires par tranches de 20min*@
                    @(h)h@(m = (m == 1 ? 0 : m))0 - @(h += (m + 2 == 6 ? 1 : 0))h@(m = (m + 2 == 6 ? 0 : m + 2))0
                </td>
                @{if (Model.Exists(x => x.CRENEAUX.HFIN == h && x.CRENEAUX.MFIN == m))
                    {
                        RDVMEDECINS.Models.RV rv = Model.ToList().Single(x => x.CRENEAUX.HFIN == h && x.CRENEAUX.MFIN == m);
                    <td>    
                        @rv.CLIENTS.TITRE @rv.CLIENTS.NOM @rv.CLIENTS.PRENOM
                    </td>
                    <td>
                        @Html.ActionLink("Supprimer", "Supprimer", new { idRv=rv.ID, idCl=rv.CLIENTS.ID, idCr=rv.CRENEAUX.ID, jour=d })
                    </td>
                    }
                    else
                    {
                    <td></td>
                    <td>
                        @Html.ActionLink("Réserver", "Reserver", new { idMed = ViewData["idMed"], hDebut = (m == 0 ? h - 1 : h), mdebut = (m == 0 ? 4 : m - 2), hFin = h, mFin = m, jour = d })
                    </td>
                    }}
            </tr>
        }
    }
</table>

RDVMEDECINS/RDVMEDECINS/Views/RDVMEDECINS/Index.cshtml
@{
    ViewBag.Title = "Index";
}@model List<RDVMEDECINS.Models.MEDECINS>

<h2>Cabinet médical - LES MEDECINS ASSOCIES</h2>
<p>
    Prise de rendez-vous :
</p>
@using (Html.BeginForm("Calendrier","RDVMEDECINS"))
{
    <label>Médecin</label>
    <select name="idMed">
        @foreach (var item in Model)
        {
            <option label="@item.TITRE @item.NOM @item.PRENOM">@item.ID</option>
        }
    </select>
    <br />
    <label>Date</label>
    <input name="jour" type="date" value="@DateTime.Today.ToString("yyyy-MM-dd")" />
    <br />
    <input type="submit" value="Valider"/>
}

RDVMEDECINS/RDVMEDECINS/Views/RDVMEDECINS/NouveauClient.cshtml
@{
    ViewBag.Title = "NouveauClient";
}

<h2>Cabinet médical - LES MEDECINS ASSOCIES</h2>

<input type="button" value="Accueil" onclick="location.href='./Index'" />

@using (Html.BeginForm())
{
    <select name="titreClient">
        <option>Mr</option>
        <option>Mme</option>
        <option>Melle</option>
    </select>
    <label>Nom</label>
    <input type="text" name="nomClient" />
    <label>Prénom</label>
    <input type="text" name="prenomClient" />
    <input hidden name="jour" value="@ViewData["jour"]" />
    <input type="submit" value="Valider" />
}

RDVMEDECINS/RDVMEDECINS/Views/RDVMEDECINS/Reserver.cshtml
@{
    ViewBag.Title = "Reserver";
}
@model List<RDVMEDECINS.Models.CLIENTS>

<h2>Cabinet médical - LES MEDECINS ASSOCIES</h2>

<input type="button" value="Accueil" onclick="location.href='./Index'" />

@{DateTime d = (DateTime)ViewData["jour"];}
<p>Rendez-vous : @(ViewData["hDebut"])h@(ViewData["mDebut"])0-@(ViewData["hFin"])h@(ViewData["mFin"])0, Jour : @d.ToString("yyyy-MM-dd"), Médecin : @ViewData["titreMed"] @ViewData["nomMed"] @ViewData["prenomMed"]  </p>

@using (Html.BeginForm())
{
    <label>Client</label>
    <select name="idClient" >
        @foreach (var item in Model)
        {
            <option label="@item.TITRE  @item.NOM  @item.PRENOM">@item.ID</option>
        }
    </select>
    <input hidden name="idMed" value="@ViewData["idMed"]"/>
    <input hidden name="hDebut" value="@ViewData["hDebut"]"/>
    <input hidden name="mDebut" value="@ViewData["mDebut"]" />
    <input hidden name="hFin" value="@ViewData["hFin"]" />
    <input hidden name="mFin" value="@ViewData["mFin"]" />
    <input hidden name="jour" value="@d.ToString("yyyy-MM-dd")" />
    <input type="submit" value="Valider"/>
    <input type="button" value="Annuler" onclick="location.href='./Index'" />
}
@using (Html.BeginForm("NouveauClient","RDVMEDECINS",FormMethod.Get))
{
    <input hidden name="idMed" value="@ViewData["idMed"]" />
    <input hidden name="hDebut" value="@ViewData["hDebut"]" />
    <input hidden name="mDebut" value="@ViewData["mDebut"]" />
    <input hidden name="hFin" value="@ViewData["hFin"]" />
    <input hidden name="mFin" value="@ViewData["mFin"]" />
    <input hidden name="jour" value="@d.ToString("yyyy-MM-dd")" />
    <input type="submit" value="Nouveau Client"/>
}

RDVMEDECINS/RDVMEDECINS/Views/RDVMEDECINS/Supprimer.cshtml
@{
    ViewBag.Title = "Supprimer";
}

<h2>Cabinet médical - LES MEDECINS ASSOCIES</h2>

<input type="button" value="Accueil" onclick="location.href='./Index'" />

@{DateTime d = (DateTime)ViewData["jour"];}
<p>Voulez-vous vraiment supprimer le rendez-vous de @ViewData["nomClient"] @ViewData["prenomClient"] le @d.ToShortDateString() @(ViewData["hDebut"])h@(ViewData["mDebut"])0-@ViewData["Hfin"]h@(ViewData["mFin"])0</p>

@using (Html.BeginForm())
{
    <input hidden name="idRv" value="@ViewData["idRv"]" />
    <input hidden name="idRv" value="@ViewData["idCr"]" />
    <input type="submit" value="Supprimer" />
    <input type="button" value="Annuler" onclick="location.href='./Index'" />
}